version: '3.8'
services:
  db_poster:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_poster'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    expose:
      - '3308'
    volumes:
      - my-db_poster:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  web:
    build: .
    environment:
      DB_URI: "mysql+pymysql://user:password@db_poster:3308/db_poster"
    ports :
      - 8091:8091
    networks:
      - default
    depends_on:
      db_poster:
        condition: service_healthy
volumes:
  my-db_poster:

networks:
  default: